# Copyright (C) 2024 Itay Weintraub ----
# This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
# you are welcome to redistribute it under certain conditions. for details,
# see the GNU General Public License Agreement (in the file COPYING.txt).
require(tidyverse) # manipulating and visualizing data
require(ggpmisc) # adding statistics to plots
# show densities along continuous time at discrete locations; 
# Input
# - dat: a data frame like the one generated by ecoevo_main.R
# Output
# - a ggplot2 figure
plot_landscape <- function(dat) {
  color_pal <- colorRampPalette(c("#56B4E9", "#009E73", "#E69F00"))
  dat  %>%
    group_by(time, species) %>%
    summarise(n=n, .groups="drop") %>%
    mutate(species=as.factor(species))%>%
    ggplot() + # create plot
    aes(x=n , xmin=0,xmax=n,y=time, colour=species, fill=species) +
    geom_ribbon(alpha=0.3) +
    coord_flip() +
    scale_x_continuous(name="density", expand=c(0.02, 0.02)) +
    scale_y_continuous(name="time (years)",labels = function(x) format(x, scientific = TRUE))+
    scale_colour_manual(values=color_pal(1)) +
    scale_fill_manual(values=color_pal(1))+
    theme(legend.position = "none",axis.text = element_text(size = 12)
          ,axis.title = element_text(size = 18))%>%
    return()
}


plot_traitLag <- function(dat,nmin) {
  color_pal <- colorRampPalette(c( "#009E73","#56B4E9", "#E69F00"))
  dat  %>% 
    group_by(time, species) %>%
    summarise(lag=Tenv-m, .groups="drop") %>%
    mutate(species=as.factor(species))%>%
    ggplot() + 
    aes(x=lag , xmin=0,xmax=lag,y=time, colour=species, fill=species) +
    geom_ribbon(alpha=0.3) +
    coord_flip() +
    scale_x_continuous(name="trait lag(°C)", expand=c(0.02, 0.02)) +
    scale_y_continuous(name="time (years)",labels = function(x) format(x, scientific = TRUE))+
    scale_colour_manual(values=color_pal(1)) +
    scale_fill_manual(values=color_pal(1))+
    theme(legend.position = "none",axis.text = element_text(size = 12)
          ,axis.title = element_text(size = 18))%>%
    return()
}
