# Copyright (C) 2024 Itay Weintraub ----
# This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
# you are welcome to redistribute it under certain conditions. for details,
# see the GNU General Public License Agreement (in the file COPYING.txt).
require(tidyverse) # manipulating and visualizing data
require(ggpmisc) # adding statistics to plots
require(scales)
# show densities across the landscape through time; works for data with
# a single model and parameterization
# Input
# - dat: a data frame like the one generated by ecoevo_main.R
# Output
# - a ggplot2 figure
plot_timeseries <- function(dat) {
  # define color gradient from cold to warm colors:
  dat %>%
    # calculate mean densities at each time and patch for each species:
    group_by(time, species, patch) %>%
    summarise(avg_n=mean(n), .groups="drop") %>%
    mutate(species=as.factor(species)) %>%
    ggplot() + # create plot
    aes(x=90/19*(patch-1), ymin=0, y=avg_n ,ymax=avg_n,fill=species, colour=species, linetype=species) +
    geom_line(alpha=1)+
    geom_ribbon(alpha=0.1)+
    facet_grid(cols=vars(time), labeller=label_bquote(col=t==.(format(time,scientific=TRUE)))) +
    coord_flip() +
    scale_x_reverse(name="latitude", expand=c(0.02, 0.02),breaks = seq(0, 90, by = 30)) +
    theme(title=element_text(size = 20), axis.text.x= element_text(size = 18),axis.text.y= element_text(size = 18),axis.title = element_text(size=20),strip.text = element_text(
      size = 18),strip.text.y = element_blank())+
    scale_y_continuous(name="population density", labels=abbreviate) %>%
    return()
}


# show densities along continuous time at discrete locations; 
# Input
# - dat: a data frame like the one generated by ecoevo_main.R
# Output
# - a ggplot2 figure
plot_landscape <- function(dat) {

  dat  %>% mutate(patch=case_when(
    (patch<=round(max(patch)/3))   ~ "Pole",
    (patch>=round(2*max(patch)/3)) ~ "Equator", 
    TRUE                           ~ "Mid")) %>%
    group_by(time, species, patch) %>%
    summarise(avg_n=mean(n), .groups="drop") %>%
    mutate(species=as.factor(species)) %>%
    ggplot() + # create plot
    aes(x=avg_n , xmin=0,xmax=avg_n,y=time, colour=species, fill=species, linetype=species) +
    geom_ribbon(alpha=0.1)+
    # panel rows: trophic level; panel columns: patch
    facet_grid(cols=vars(patch), labeller=label_bquote(col=.(patch))) +
    coord_flip() +
    scale_x_continuous(name="density", expand=c(0.02, 0.02)) +
    theme(title=element_text(size = 20), axis.text.x= element_text(size = 18,angle = 45, vjust = 0.5, hjust=0.5),axis.text.y= element_text(size = 18),axis.title = element_text(size=20),strip.text = element_text(
      size = 18),strip.text.y = element_blank())+
    scale_y_continuous(name="time (years)", labels = function(x) format(x, scientific = TRUE)) %>%
    return()
}